### PR TITLE
#2236: run screengrab subprocess in clean env

### PR DESCRIPTION
**Pull request by aparna-d2**
Depends on https://github.com/mbrainerd/tk-core/pull/35

### CODE REVIEW

**Review by mbrainerd — COMMENTED** [review]
Is there a way to do this without embedding dd-specific logic? Put another way, could this solution be generalized, and then use abstraction to afford the dd changes either in dd_jstools_utils or sgtk_config?

**Comment by aparna-d2** [comment]
We'd have to put in a hook - maybe make a hook for _external_screenshot(), because depending on `import` feels like something a studio should be able to override...shall I do that instead? Then we can put the jstools logic in sgtk_config.

**Comment by aparna-d2** [comment]
Went ahead with the hook.

**Review by mbrainerd — APPROVED** [review]
Looks great, thanks

**Comment by aparna-d2** [comment]
No permission to merge. Add me as collaborator?

**Pull request merged**
